name: Generate MultiSnake

on:
  schedule:
    - cron: "0 */6 * * *" # 每6小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 检出仓库代码
      - name: Checkout the repository
        uses: actions/checkout@v2

      # 生成 Github Snake 动画
      - name: Generate MultiSource Snake animation
        uses: Zqzqsb/MultiSourceSnake@v0.5
        with:
          GITHUB_USER: Zqzqsb
          GITEE_USER: zqzqsb
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEE_TOKEN: f35530eaa371caac21241b628c123444

      # 验证生成的文件是否存在
      - name: Verify output files
        run: |
          ls -al ${{ github.workspace }}

      # 将生成的动画推送到 output 分支
      - name: Push GitHub Snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: /action-release/output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
